name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'index.html'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::098412623305:role/cloudresumerole
        aws-region: ap-south-1

    - name: Deploy index.html to S3
      run: aws s3 cp index.html s3://venkatraman-resume-aws/

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id E3AFALU2RASPI4 --paths "/index.html"

